set_property SRC_FILE_INFO {cfile:C:/Users/Student/Desktop/152BFall25/CSM152B/Lab_3_3_Copy/Lab_3_3.srcs/constrs_1/new/Basys-3-Master.xdc rfile:../../../Lab_3_3.srcs/constrs_1/new/Basys-3-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports clk]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
